"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import django_heroku
from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'Ecbdcc7489Cf5477C8Fd51F1F30Db4E9A50Baaafe8C8743A'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "e-commerce6.herokuapp.com", "nileware.org", "localhost", "127.0.0.1"
]

# Application definition

INSTALLED_APPS = [
    "modeltranslation",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.sites",
    "django.contrib.staticfiles",
    "home.apps.HomeConfig",
    "product.apps.ProductConfig",
    "order.apps.OrderConfig",
    "vendor.apps.VendorConfig",
    "user.apps.UserConfig",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.facebook",
    "allauth.socialaccount.providers.google",
    "payment.apps.PaymentConfig",
    "cart.apps.CartConfig",
    "coupons.apps.CouponsConfig",
    "ckeditor",
    "ckeditor_uploader",
    "mptt",
    "admin_thumbnails",
    "paypal.standard.ipn",
    "rosetta",
    "import_export",
    "django_admin_listfilter_dropdown",
    "crispy_forms",
    "social_django",
    "django_extensions",
    "currencies",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "home.context_processors.totalprice",
                # 'django.core.context_processors.request',
                "currencies.context_processors.currencies",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": "pounds",
#         "USER": "root",
#         "PASSWORD": "",
#         "HOST": "127.0.0.1",
#         "PORT": "",
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME":
        "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME":
        "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/
LANGUAGES = [
    ("en", _("English")),
    ("ar", _("Arabic")),
]

LANGUAGE_CODE = "en-us"
MODELTRANSLATION_TRANSLATION_FILES = (
    # "home.translation",
    "product.translation", )

LOCALE_PATHS = (os.path.join(BASE_DIR, "locale"), )
TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

####### currency config
DEFAULT_CURRENCY = "EGP"
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_ROOT = os.path.join(
    BASE_DIR,
    "static",
)
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "project/static"),
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# ...
SITE_ID = 1

####################################
##  CKEDITOR CONFIGURATION ##
####################################

CKEDITOR_JQUERY_URL = "https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"

CKEDITOR_UPLOAD_PATH = "images/"
CKEDITOR_IMAGE_BACKEND = "pillow"

CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": None,
    },
}

###########################################
############### email message #############
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = "ahmedahmedfekry11305654@gmail.com"
EMAIL_HOST_PASSWORD = "vqqqqikuzhrqbskt"
EMAIL_USE_TLS = True
EMAIL_PORT = "587"
######## paypal###############
PAYPAL_TEST = True

PAYPAL_RECEIVER_EMAIL = "sb-jlagl4365434@business.example.com"

ROSETTA_SHOW_AT_ADMIN_PANEL = True
# ROSETTA_EXCLUDED_APPLICATIONS = "allauth"
CART_SESSION_ID = "cart"
CRISPY_TEMPLATE_PACK = "bootstrap3"
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "user.authentication.EmailAuthBackend",
    # "social_core.backends.facebook.FacebookOAuth2",
    # 'social_core.backends.twitter.TwitterOAuth',
    # 'social_core.backends.google.GoogleOAuth2',
]
LOGIN_REDIRECT_URL = "/"
# SOCIAL_AUTH_FACEBOOK_KEY = "148278460514239"  # Facebook App ID
# SOCIAL_AUTH_FACEBOOK_SECRET = "7213194b4726d96fef91dfde6a823f06"  # Facebook App Secret
# SOCIAL_AUTH_FACEBOOK_SCOPE = ["email"]
# TRANSLATABLE_MODEL_MODULES = ["product.models",]

######## whitenoise
IS_MONOLINGUAL = False
TRANSLATABLE_MODEL_MODULES = ["product.models"]

django_heroku.settings(locals())
